package pmacct

import (
	"fmt"
	"net"
	"regexp"
	"strings"
)

var pmacctInstanceNamePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$`)

// validatePmacctInstanceName protects every remote path and service name that
// is derived from an instance name. Names are generated by the panel, but the
// database can also contain imported/legacy records, so callers must validate
// before constructing shell scripts or SFTP paths.
func validatePmacctInstanceName(name string) error {
	clean := strings.TrimSpace(name)
	if clean == "" || clean != name || !pmacctInstanceNamePattern.MatchString(clean) {
		return fmt.Errorf("invalid pmacct instance name %q", name)
	}
	return nil
}

func normalizePmacctQueryIP(value string) (string, error) {
	clean := strings.TrimSpace(value)
	if clean == "" {
		return "", fmt.Errorf("empty address")
	}
	if slash := strings.IndexByte(clean, '/'); slash >= 0 {
		if _, _, err := net.ParseCIDR(clean); err != nil {
			return "", fmt.Errorf("invalid CIDR %q", value)
		}
		clean = clean[:slash]
	}
	parsed := net.ParseIP(clean)
	if parsed == nil {
		return "", fmt.Errorf("invalid address %q", value)
	}
	return parsed.String(), nil
}
