package source

import "strings"

const defaultTemplates = `https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_18.04_bionic_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_18.04_bionic_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_20.04_focal_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_20.04_focal_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_22.04_jammy_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_22.04_jammy_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_23.04_lunar_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_23.04_lunar_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_23.10_mantic_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_23.10_mantic_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_24.04_noble_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/ubuntu/ubuntu_24.04_noble_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/rockylinux/rockylinux_8_8_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/rockylinux/rockylinux_8_8_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/rockylinux/rockylinux_9_9_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/rockylinux/rockylinux_9_9_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/oracle/oracle_8_8_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/oracle/oracle_9_9_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_21.02_21.02_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_21.02_21.02_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_22.03_22.03_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_22.03_22.03_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_23.05_23.05_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_23.05_23.05_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_24.10_24.10_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_24.10_24.10_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_snapshot_snapshot_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openwrt/openwrt_snapshot_snapshot_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_15.4_15.4_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_15.4_15.4_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_15.5_15.5_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_15.5_15.5_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_15.6_15.6_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_15.6_15.6_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_16.0_16.0_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_16.0_16.0_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_20.03_20.03_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_20.03_20.03_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_22.03_22.03_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_22.03_22.03_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_23.03_23.03_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_23.03_23.03_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_23.09_23.09_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_23.09_23.09_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_24.03_24.03_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_24.03_24.03_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_24.09_24.09_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_24.09_24.09_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_25.03_25.03_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_25.03_25.03_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_25.09_25.09_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/openeuler/openeuler_25.09_25.09_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/kali/kali_latest_kali-rolling_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/kali/kali_latest_kali-rolling_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/gentoo/gentoo_current_current_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/gentoo/gentoo_current_current_x86_64_openrc.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/gentoo/gentoo_current_current_x86_64_systemd.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_37_37_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_37_37_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_38_38_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_38_38_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_39_39_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_39_39_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_40_40_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/fedora/fedora_40_40_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_10_buster_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_10_buster_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_11_bullseye_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_11_bullseye_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_12_bookworm_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_12_bookworm_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_13_trixie_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/debian/debian_13_trixie_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/centos/centos_7_7_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/centos/centos_7_7_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/centos/centos_8_8-Stream_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/centos/centos_8_8-Stream_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/centos/centos_9_9-Stream_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/centos/centos_9_9-Stream_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/archlinux/archlinux_current_current_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/archlinux/archlinux_current_current_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.16_3.16_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.17_3.17_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.18_3.18_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.19_3.19_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.20_3.20_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.21_3.21_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.22_3.22_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_3.23_3.23_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/alpine/alpine_edge_edge_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/almalinux/almalinux_8_8_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/almalinux/almalinux_8_8_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/almalinux/almalinux_9_9_x86_64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_amd64_images/releases/download/almalinux/almalinux_9_9_x86_64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openwrt/openwrt_23.05_23.05_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openwrt/openwrt_23.05_23.05_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openwrt/openwrt_snapshot_snapshot_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openwrt/openwrt_snapshot_snapshot_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/archlinux/archlinux_current_current_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/archlinux/archlinux_current_current_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_18.04_bionic_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_18.04_bionic_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_20.04_focal_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_20.04_focal_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_22.04_jammy_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_22.04_jammy_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_23.04_lunar_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_23.04_lunar_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_23.10_mantic_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_23.10_mantic_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_24.04_noble_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/ubuntu/ubuntu_24.04_noble_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/rockylinux/rockylinux_8_8_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/rockylinux/rockylinux_8_8_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/rockylinux/rockylinux_9_9_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/rockylinux/rockylinux_9_9_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/oracle/oracle_8_8_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_15.4_15.4_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_15.4_15.4_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_15.5_15.5_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_15.5_15.5_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_15.6_15.6_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_15.6_15.6_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_16.0_16.0_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_16.0_16.0_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_20.03_20.03_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_20.03_20.03_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_22.03_22.03_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_22.03_22.03_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_23.09_23.09_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_23.09_23.09_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_24.03_24.03_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_24.03_24.03_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_25.03_25.03_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_25.03_25.03_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_25.09_25.09_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/openeuler/openeuler_25.09_25.09_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/kali/kali_latest_kali-rolling_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/kali/kali_latest_kali-rolling_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/gentoo/gentoo_current_current_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/gentoo/gentoo_current_current_arm64_openrc.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/gentoo/gentoo_current_current_arm64_systemd.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_37_37_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_37_37_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_38_38_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_38_38_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_39_39_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_39_39_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_40_40_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/fedora/fedora_40_40_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_10_buster_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_10_buster_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_11_bullseye_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_11_bullseye_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_12_bookworm_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_12_bookworm_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_13_trixie_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/debian/debian_13_trixie_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/centos/centos_7_7_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/centos/centos_7_7_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/centos/centos_8_8-Stream_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/centos/centos_8_8-Stream_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/centos/centos_9_9-Stream_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/centos/centos_9_9-Stream_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.16_3.16_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.17_3.17_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.18_3.18_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.19_3.19_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.20_3.20_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.21_3.21_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.22_3.22_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_3.23_3.23_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/alpine/alpine_edge_edge_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/almalinux/almalinux_8_8_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/almalinux/almalinux_8_8_arm64_default.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/almalinux/almalinux_9_9_arm64_cloud.tar.xz
https://github.com/oneclickvirt/lxc_arm_images/releases/download/almalinux/almalinux_9_9_arm64_default.tar.xz
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/almalinux_8_8_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/almalinux_8_8_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/almalinux_8_8_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/almalinux_8_8_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.17_3.17_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.17_3.17_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.17_3.17_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.17_3.17_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.18_3.18_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.18_3.18_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.18_3.18_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.18_3.18_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.19_3.19_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.19_3.19_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.19_3.19_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_3.19_3.19_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_edge_edge_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_edge_edge_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_edge_edge_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/alpine_edge_edge_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/archlinux_current_current_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/archlinux_current_current_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/archlinux_current_current_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/archlinux_current_current_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_11_bullseye_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_11_bullseye_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_11_bullseye_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_11_bullseye_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_12_bookworm_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_12_bookworm_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_12_bookworm_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_12_bookworm_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_13_trixie_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_13_trixie_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_13_trixie_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/debian_13_trixie_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/fedora_41_41_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/fedora_41_41_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/fedora_41_41_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/fedora_41_41_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/gentoo_current_current_amd64_openrc_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/gentoo_current_current_amd64_systemd_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/gentoo_current_current_arm64_openrc_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/gentoo_current_current_arm64_systemd_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/kali_latest_kali-rolling_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/kali_latest_kali-rolling_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/kali_latest_kali-rolling_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/kali_latest_kali-rolling_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/openeuler_24.03_24.03_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/openeuler_24.03_24.03_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_15.6_15.6_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_15.6_15.6_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_15.6_15.6_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_15.6_15.6_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/oracle_8_8_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/oracle_8_8_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/oracle_9_9_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/oracle_9_9_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/rockylinux_8_8_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/rockylinux_8_8_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_18.04_bionic_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_18.04_bionic_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_18.04_bionic_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_18.04_bionic_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_20.04_focal_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_20.04_focal_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_20.04_focal_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_20.04_focal_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_22.04_jammy_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_22.04_jammy_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_22.04_jammy_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_22.04_jammy_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_24.04_noble_amd64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_24.04_noble_amd64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_24.04_noble_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kvm_images/ubuntu_24.04_noble_arm64_default_kvm.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_18.04_bionic_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_18.04_bionic_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_18.04_bionic_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_18.04_bionic_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_20.04_focal_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_20.04_focal_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_20.04_focal_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_20.04_focal_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_22.04_jammy_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_22.04_jammy_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_22.04_jammy_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_22.04_jammy_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_24.04_noble_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_24.04_noble_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_24.04_noble_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/ubuntu/ubuntu_24.04_noble_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_8_8_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_8_8_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_8_8_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_8_8_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_9_9_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_9_9_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_9_9_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/rockylinux/rockylinux_9_9_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/oracle/oracle_7_7_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/oracle/oracle_7_7_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/oracle/oracle_8_8_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/oracle/oracle_8_8_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/oracle/oracle_9_9_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/oracle/oracle_9_9_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_15.6_15.6_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_15.6_15.6_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_15.6_15.6_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_15.6_15.6_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/openeuler/openeuler_24.03_24.03_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/openeuler/openeuler_24.03_24.03_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/openeuler/openeuler_24.03_24.03_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/openeuler/openeuler_24.03_24.03_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kali/kali_latest_kali-rolling_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kali/kali_latest_kali-rolling_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kali/kali_latest_kali-rolling_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/kali/kali_latest_kali-rolling_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/gentoo/gentoo_current_current_amd64_openrc.zip
https://github.com/oneclickvirt/lxd_images/releases/download/gentoo/gentoo_current_current_amd64_systemd.zip
https://github.com/oneclickvirt/lxd_images/releases/download/gentoo/gentoo_current_current_arm64_openrc.zip
https://github.com/oneclickvirt/lxd_images/releases/download/gentoo/gentoo_current_current_arm64_systemd.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_40_40_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_40_40_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_40_40_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_40_40_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_41_41_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_41_41_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_41_41_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/fedora/fedora_41_41_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_11_bullseye_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_11_bullseye_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_11_bullseye_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_11_bullseye_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_12_bookworm_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_12_bookworm_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_12_bookworm_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_12_bookworm_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_13_trixie_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_13_trixie_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_13_trixie_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/debian/debian_13_trixie_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/archlinux/archlinux_current_current_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/archlinux/archlinux_current_current_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/archlinux/archlinux_current_current_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/archlinux/archlinux_current_current_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.17_3.17_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.17_3.17_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.18_3.18_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.18_3.18_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.19_3.19_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.19_3.19_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.20_3.20_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.20_3.20_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.21_3.21_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_3.21_3.21_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_edge_edge_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/alpine/alpine_edge_edge_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_8_8_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_8_8_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_8_8_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_8_8_arm64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_9_9_amd64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_9_9_amd64_default.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_9_9_arm64_cloud.zip
https://github.com/oneclickvirt/lxd_images/releases/download/almalinux/almalinux_9_9_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/almalinux_8_8_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/almalinux_8_8_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/almalinux_8_8_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/almalinux_8_8_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.19_3.19_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.19_3.19_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.19_3.19_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.19_3.19_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.20_3.20_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.20_3.20_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.20_3.20_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.20_3.20_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.21_3.21_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.21_3.21_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.21_3.21_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.21_3.21_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.22_3.22_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.22_3.22_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.22_3.22_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.22_3.22_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.23_3.23_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.23_3.23_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.23_3.23_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_3.23_3.23_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_edge_edge_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_edge_edge_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_edge_edge_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/alpine_edge_edge_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/archlinux_current_current_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/archlinux_current_current_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/archlinux_current_current_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/archlinux_current_current_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_11_bullseye_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_11_bullseye_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_11_bullseye_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_11_bullseye_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_12_bookworm_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_12_bookworm_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_12_bookworm_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_12_bookworm_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_13_trixie_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_13_trixie_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_13_trixie_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/debian_13_trixie_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_20.03_20.03_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_20.03_20.03_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_22.03_22.03_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_22.03_22.03_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_24.03_24.03_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_24.03_24.03_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_25.03_25.03_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_25.03_25.03_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_25.09_25.09_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openeuler_25.09_25.09_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.5_15.5_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.5_15.5_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.5_15.5_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.5_15.5_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.6_15.6_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.6_15.6_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.6_15.6_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_15.6_15.6_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_16.0_16.0_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_16.0_16.0_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_16.0_16.0_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_16.0_16.0_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/opensuse_tumbleweed_tumbleweed_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/oracle_8_8_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/oracle_8_8_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/oracle_9_9_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/oracle_9_9_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/openwrt_24.10_24.10_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/rockylinux_8_8_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/rockylinux_8_8_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/rockylinux_8_8_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/rockylinux_8_8_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_18.04_bionic_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_18.04_bionic_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_18.04_bionic_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_18.04_bionic_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_20.04_focal_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_20.04_focal_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_20.04_focal_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_20.04_focal_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_22.04_jammy_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_22.04_jammy_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_22.04_jammy_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_22.04_jammy_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_24.04_noble_arm64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_24.04_noble_arm64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_24.04_noble_x86_64_cloud_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/kvm_images/ubuntu_24.04_noble_x86_64_default_kvm.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.4_15.4_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.4_15.4_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.5_15.5_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.5_15.5_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.5_15.5_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.5_15.5_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.6_15.6_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.6_15.6_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.6_15.6_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_15.6_15.6_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_16.0_16.0_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_16.0_16.0_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_16.0_16.0_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_16.0_16.0_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/opensuse/opensuse_tumbleweed_tumbleweed_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_20.03_20.03_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_20.03_20.03_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_20.03_20.03_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_20.03_20.03_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_22.03_22.03_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_22.03_22.03_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_22.03_22.03_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_22.03_22.03_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_23.03_23.03_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_23.03_23.03_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_23.09_23.09_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_23.09_23.09_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.03_24.03_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.03_24.03_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.03_24.03_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.03_24.03_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.09_24.09_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.09_24.09_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.09_24.09_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_24.09_24.09_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.03_25.03_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.03_25.03_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.03_25.03_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.03_25.03_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.09_25.09_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.09_25.09_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.09_25.09_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openeuler/openeuler_25.09_25.09_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/gentoo/gentoo_current_current_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/gentoo/gentoo_current_current_arm64_openrc.zip
https://github.com/oneclickvirt/incus_images/releases/download/gentoo/gentoo_current_current_arm64_systemd.zip
https://github.com/oneclickvirt/incus_images/releases/download/gentoo/gentoo_current_current_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/gentoo/gentoo_current_current_x86_64_openrc.zip
https://github.com/oneclickvirt/incus_images/releases/download/gentoo/gentoo_current_current_x86_64_systemd.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_37_37_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_37_37_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_38_38_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_38_38_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_39_39_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_39_39_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_39_39_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_39_39_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_40_40_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_40_40_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_40_40_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/fedora/fedora_40_40_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_18.04_bionic_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_18.04_bionic_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_18.04_bionic_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_18.04_bionic_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_20.04_focal_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_20.04_focal_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_20.04_focal_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_20.04_focal_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_22.04_jammy_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_22.04_jammy_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_22.04_jammy_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_22.04_jammy_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_23.04_lunar_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_23.04_lunar_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_23.10_mantic_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_23.10_mantic_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_24.04_noble_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_24.04_noble_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_24.04_noble_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/ubuntu/ubuntu_24.04_noble_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_8_8_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_8_8_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_8_8_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_8_8_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_9_9_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_9_9_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_9_9_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/rockylinux/rockylinux_9_9_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/oracle/oracle_8_8_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/oracle/oracle_8_8_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/oracle/oracle_9_9_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/oracle/oracle_9_9_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_21.02_21.02_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_21.02_21.02_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_22.03_22.03_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_22.03_22.03_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_23.05_23.05_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_23.05_23.05_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_snapshot_snapshot_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/openwrt/openwrt_snapshot_snapshot_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/kali/kali_latest_kali-rolling_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/kali/kali_latest_kali-rolling_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/kali/kali_latest_kali-rolling_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/kali/kali_latest_kali-rolling_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_10_buster_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_10_buster_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_10_buster_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_10_buster_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_11_bullseye_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_11_bullseye_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_11_bullseye_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_11_bullseye_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_12_bookworm_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_12_bookworm_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_12_bookworm_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_12_bookworm_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_13_trixie_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_13_trixie_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_13_trixie_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/debian/debian_13_trixie_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_7_7_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_7_7_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_8_8-Stream_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_8_8-Stream_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_9_9-Stream_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_9_9-Stream_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_9_9-Stream_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/centos/centos_9_9-Stream_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/archlinux/archlinux_current_current_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/archlinux/archlinux_current_current_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/archlinux/archlinux_current_current_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/archlinux/archlinux_current_current_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.16_3.16_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.17_3.17_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.18_3.18_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.18_3.18_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.19_3.19_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.19_3.19_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.20_3.20_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.20_3.20_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.21_3.21_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.21_3.21_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.22_3.22_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.22_3.22_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.23_3.23_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_3.23_3.23_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_edge_edge_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/alpine/alpine_edge_edge_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_8_8_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_8_8_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_8_8_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_8_8_x86_64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_9_9_arm64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_9_9_arm64_default.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_9_9_x86_64_cloud.zip
https://github.com/oneclickvirt/incus_images/releases/download/almalinux/almalinux_9_9_x86_64_default.zip
https://github.com/oneclickvirt/docker/releases/download/ubuntu/spiritlhl_ubuntu_amd64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/ubuntu/spiritlhl_ubuntu_arm64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/rockylinux/spiritlhl_rockylinux_amd64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/rockylinux/spiritlhl_rockylinux_arm64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/openeuler/spiritlhl_openeuler_amd64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/openeuler/spiritlhl_openeuler_arm64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/debian/spiritlhl_debian_amd64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/debian/spiritlhl_debian_arm64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/alpine/spiritlhl_alpine_amd64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/alpine/spiritlhl_alpine_arm64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/almalinux/spiritlhl_almalinux_amd64.tar.gz
https://github.com/oneclickvirt/docker/releases/download/almalinux/spiritlhl_almalinux_arm64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/ubuntu/spiritlhl_ubuntu_amd64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/ubuntu/spiritlhl_ubuntu_arm64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/rockylinux/spiritlhl_rockylinux_amd64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/rockylinux/spiritlhl_rockylinux_arm64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/openeuler/spiritlhl_openeuler_amd64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/openeuler/spiritlhl_openeuler_arm64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/debian/spiritlhl_debian_amd64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/debian/spiritlhl_debian_arm64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/alpine/spiritlhl_alpine_amd64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/alpine/spiritlhl_alpine_arm64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/almalinux/spiritlhl_almalinux_amd64.tar.gz
https://github.com/oneclickvirt/podman/releases/download/almalinux/spiritlhl_almalinux_arm64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/ubuntu/spiritlhl_ubuntu_amd64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/ubuntu/spiritlhl_ubuntu_arm64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/rockylinux/spiritlhl_rockylinux_amd64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/rockylinux/spiritlhl_rockylinux_arm64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/openeuler/spiritlhl_openeuler_amd64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/openeuler/spiritlhl_openeuler_arm64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/debian/spiritlhl_debian_amd64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/debian/spiritlhl_debian_arm64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/alpine/spiritlhl_alpine_amd64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/alpine/spiritlhl_alpine_arm64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/almalinux/spiritlhl_almalinux_amd64.tar.gz
https://github.com/oneclickvirt/containerd/releases/download/almalinux/spiritlhl_almalinux_arm64.tar.gz
https://github.com/oneclickvirt/pve_kvm_images/releases/download/centos/centos8.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/centos/centos9.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/archlinux/archlinux-latest.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/ubuntu/ubuntu1804.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/ubuntu/ubuntu2004.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/ubuntu/ubuntu2204.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/ubuntu/ubuntu2404.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/rockylinux/rockylinux8.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/rockylinux/rockylinux9.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/debian/debian11.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/debian/debian12.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/debian/debian13.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/alpine/alpine3.20.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/alpine/alpine3.21.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/alpine/alpine3.22.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/almalinux/almalinux10.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/almalinux/almalinux8.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/almalinux/almalinux9.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/almalinux8.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/almalinux9.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/alpinelinux_edge.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/alpinelinux_stable.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/centos10-stream.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/centos7.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/centos8-stream.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/centos9-stream.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/debian11.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/debian12.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/rockylinux8.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/rockylinux9.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/ubuntu18.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/ubuntu20.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/ubuntu22.qcow2
https://github.com/oneclickvirt/pve_kvm_images/releases/download/images/ubuntu24.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/debian11/debian11.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/debian12/debian12.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/ubuntu22/ubuntu22.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/ubuntu24/ubuntu24.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/almalinux9/almalinux9.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/rockylinux9/rockylinux9.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/centos7/centos7.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/centos8-stream/centos8-stream.qcow2
https://github.com/oneclickvirt/kvm_images/releases/download/opensuse-leap-15/opensuse-leap-15.qcow2
https://download.testip.xyz/Windows-VirtIO/virtio_zh-cn_windows_server_2019_x64_dvd_19d65722.iso
https://download.testip.xyz/Windows-VirtIO/virtio_zh-cn_windows_server_2022_updated_nov_2022_x64_dvd_78530c38.iso
https://download.testip.xyz/windows/zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.iso
https://download.testip.xyz/windows/en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso
https://download.testip.xyz/windows/zh-cn_windows_11_enterprise_ltsc_2024_x64_dvd_cff9cd2d.iso
https://download.testip.xyz/windows/en-us_windows_11_enterprise_ltsc_2024_x64_dvd_965cfb00.iso
https://download.testip.xyz/windows/zh-cn_windows_server_2019_x64_dvd_19d65722.iso
https://download.testip.xyz/windows/en-us_windows_server_2019_x64_dvd_f9475476.iso
https://download.testip.xyz/windows/zh-cn_windows_server_2022_updated_may_2026_x64_dvd_c4723e47.iso
https://download.testip.xyz/windows/en-us_windows_server_2022_updated_may_2026_x64_dvd_c4723e47.iso
https://github.com/oneclickvirt/macos/releases/download/images/high-sierra.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/mojave.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/catalina.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/big-sur.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/monterey.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/ventura.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/sonoma.iso.7z
https://github.com/oneclickvirt/macos/releases/download/images/sequoia.iso.7z
https://mirrors.tuna.tsinghua.edu.cn/osdn/android-x86/71931/android-x86_64-9.0-r2.iso
https://mirrors.tuna.tsinghua.edu.cn/osdn/android-x86/71931/android-x86_64-9.0-rc2.iso
https://sourceforge.net/projects/blissos-x86/files/Official/BlissOS15/Gapps/Generic/Bliss-v15.9.2-x86_64-OFFICIAL-gapps-20241012.iso/download
docker://spiritlhl/wds:10
docker://spiritlhl/wds:2019
docker://spiritlhl/wds:2022
docker://redroid/redroid:8.1.0-latest
docker://redroid/redroid:9.0.0-latest
docker://redroid/redroid:10.0.0-latest
docker://redroid/redroid:11.0.0-latest
docker://redroid/redroid:12.0.0-latest
docker://dockurr/macos:11
docker://dockurr/macos:12
docker://dockurr/macos:13
docker://dockurr/macos:14
docker://dockurr/macos:15`

// getDefaultImageURLs 返回内置镜像URL列表。
// 默认同步会把该列表作为远程列表的补充；远程不可用时则完全使用该列表初始化。
func getDefaultImageURLs() []string {
	lines := strings.Split(defaultTemplates, "\n")
	urls := make([]string, 0, len(lines))

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" && (strings.HasPrefix(line, "https://") || strings.HasPrefix(line, "docker://")) {
			urls = append(urls, line)
		}
	}
	return urls
}
